# Solar Powered Refrigerator

solar_power = float(input("Enter solar panel power (W): "))
sun_hours = float(input("Enter sunlight hours per day: "))
fridge_power = float(input("Enter refrigerator power consumption (W): "))
fridge_hours = float(input("Enter refrigerator operating hours per day: "))
battery_capacity = float(input("Enter battery capacity (Wh): "))

# Energy generated by solar panel
solar_energy = solar_power * sun_hours

# Energy required by refrigerator
fridge_energy = fridge_power * fridge_hours

# Energy available after running refrigerator
net_energy = solar_energy - fridge_energy

print("\n--- Solar Powered Refrigerator ---")
print(f"Solar energy generated: {solar_energy:.2f} Wh")
print(f"Refrigerator energy required: {fridge_energy:.2f} Wh")

if solar_energy >= fridge_energy:
    print("Solar energy is sufficient.")
    print(f"Energy remaining: {net_energy:.2f} Wh")
else:
    extra_energy = fridge_energy - solar_energy
    print("Solar energy is insufficient.")
    print(f"Battery energy required: {extra_energy:.2f} Wh")

    if extra_energy <= battery_capacity:
        print("Battery can supply the remaining energy.")
    else:
        print("Battery capacity is insufficient.")
